name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: rg-eshoponweb
  LOCATION: westus2
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 9ddceb62-5f5d-4e71-b3db-e161f9c0d948
  WEBAPP-NAME: eshoponweb-webapp-feb2025

jobs:
  buildandtest:
    runs-on: ubuntu-22.04   # safer pinning
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'   # stable SDK

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release

    - name: dotnet publish
      run: |
        dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        cd ${{env.DOTNET_ROOT}}/myapp
        zip -r app.zip .

    - name: Upload artifact for deployment job (webapp)
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp/app.zip

    - name: Upload artifact for deployment job (bicep)
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}

  deploy:
    runs-on: ubuntu-22.04
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    - name: Download artifact from build job (webapp)
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: .net-app

    - name: Download artifact from build job (bicep)
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: bicep-template

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infrastructure
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION-ID }}
        resourceGroupName: ${{ env.RESOURCE-GROUP }}
        template: bicep-template/webapp.bicep
        parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
        failOnStdErr: false

    - name: Publish Website to WebApp
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az webapp deploy \
            --name ${{ env.WEBAPP-NAME }} \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --src-path .net-app/app.zip \
            --type zip
